# -*- coding: utf-8 -*-
import random
import time
import winsound
# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from threading import Thread
from PyQt5 import QtCore,  QtWidgets
class MUYU:
    def __init__(self):
        self.__kind = 0
    def get_kind(self):
        return self.__kind

    def add_kind(self):
        self.__kind += 1


class Ui_Form(object):
    def setupUi(self, Form):

        Form.setObjectName("Form")
        Form.resize(553, 351)
        self.kind = MUYU()
        self.op = QtWidgets.QGraphicsOpacityEffect()
        self.op.setOpacity(0)

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton2 = QtWidgets.QPushButton(Form)
        self.pushButton2.setGraphicsEffect(self.op)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 580, 370))
        self.pushButton2.setGeometry(QtCore.QRect(460, 80, 80, 40))
        self.pushButton.setStyleSheet("border-image: url(res/1.png);border:None")
        self.pushButton2.setStyleSheet("border-image: url(res/plus.jpg);")
        self.pushButton.setText("")
        self.pushButton2.setText("")
        Form.setFixedSize(553, 351)

        # op = QtWidgets.QGraphicsOpacityEffect()
        # # 设置透明度的值，0.0到1.0，最小值0是透明，1是不透明
        # op.setOpacity(0)
        # self.pushButton.setGraphicsEffect(op)

        self.pushButton.setObjectName("pushButton")
        self.pushButton2.setObjectName("pushButton2")

        self.retranslateUi(Form)
        self.pushButton.pressed.connect(self.press)
        self.pushButton.released.connect(self.release)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "点击佛祖原谅你"))

    def press(self):
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 570, 360))
        Thread(target=self.slowly_display).start()
        Thread(target=self.play_sound).start()


    def release(self):
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 580, 370))
        self.kind.add_kind()



    def slowly_display(self):

        self.op.setOpacity(0.2)
        time.sleep(0.03)
        self.op.setOpacity(0.4)
        time.sleep(0.03)
        self.op.setOpacity(0.6)
        time.sleep(0.03)
        self.op.setOpacity(0.8)
        time.sleep(0.03)
        self.op.setOpacity(1)
        time.sleep(0.03)
        self.op.setOpacity(0.8)
        time.sleep(0.03)
        self.op.setOpacity(0.6)
        time.sleep(0.03)
        self.op.setOpacity(0.4)
        time.sleep(0.03)
        self.op.setOpacity(0.2)
        time.sleep(0.03)
        self.op.setOpacity(0)

    def play_sound(self):
        winsound.PlaySound("res/1.wav", winsound.SND_ASYNC)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
